version: "3.9"
services:
  tyds-web:
    build: .
    container_name: tyds-next15
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
